### ISSUE TITLE
Get Notifications request -> user_id, business_data_id로 변경

### ISSUE THREAD

**Issue by dannaward** [marhaedgh/rbln-infer-server#14]
- 클라이언트에서 요청시 422 에러 나는 이슈 (정확한 원인이 이건지는 모르겠으나 이것부터 해결하고 갑시다)

**Comment by WagyuShark** [comment]
Get Notifications Request에서 user_id만 사용중이고, business_data_id는 Notification Service 의 get_notifications_by_business_data 라는 레거시 함수에서 사용하던 데이터입니다.
그래서 다른 부분에서 오류가 나는 것 같습니다. @dannaward

**Comment by dannaward** [comment]
옙! 어차피 이게 해결 안 되면 클라이언트 연결을 못 하니까 원인 파악해서 수정해주십셔!
진행상황은 이 이슈에서 계속 이야기합시다
